### ISSUE TITLE
Add Compatibility with mouse tooltips

### ISSUE THREAD

**Issue by kulcris** [Koitere/monster-stats#1]
![image](https://github.com/user-attachments/assets/25538f39-e061-419d-96d3-595e48626c58)
Please see the attached image

**Comment by Koitere** [comment]
Hey Kulcris,

Thanks for putting in an issue! I'm currently working on v1.1 which should be ready within the next couple days. I will ensure this is fixed in v1.1, I usually use this plugin but must have turned it off at some point and missed this.

Thanks,
Koitere

**Comment by Koitere** [comment]
Fixed in version v1.1, pending Runelite approval.
